plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-kapt'
    id 'androidx.navigation.safeargs.kotlin'
    id 'com.google.android.libraries.mapsplatform.secrets-gradle-plugin'
    id 'com.google.gms.google-services'
}

android {
    namespace 'com.demo.sharingapp'
    compileSdk 33

    defaultConfig {
        applicationId "com.demo.sharingapp"
        minSdk 28
        targetSdk 33
        versionCode 3
        versionName "1.2"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }

    viewBinding{
        enabled = true
    }
}

dependencies {


    implementation 'androidx.core:core-ktx:1.7.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'


    //카카오톡
    implementation "com.kakao.sdk:v2-user:2.20.1" // 카카오 로그인

    //레트로핏
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'

    //okhttp
    implementation(platform("com.squareup.okhttp3:okhttp-bom:4.11.0"))

    // define any required OkHttp artifacts without version
    implementation("com.squareup.okhttp3:okhttp")
    implementation("com.squareup.okhttp3:logging-interceptor")

    // glide
    implementation 'com.github.bumptech.glide:glide:4.14.2'

    //Gson
    implementation 'com.google.code.gson:gson:2.10.1'

    //Navigation
    implementation("androidx.navigation:navigation-fragment-ktx:2.5.3")
    implementation("androidx.navigation:navigation-ui-ktx:2.5.3")

    //SharedPreference
    implementation 'androidx.security:security-crypto-ktx:1.1.0-alpha04'

    //코루틴
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.4.2'

    //구글맵
    implementation 'com.google.android.gms:play-services-maps:18.1.0'

    // 포토뷰
    implementation 'com.github.chrisbanes:PhotoView:2.3.0'

    // 구글 플레이 서비스
    implementation 'com.google.android.gms:play-services-location:21.0.1'
    
    // roundedImageView
    implementation 'com.makeramen:roundedimageview:2.3.0'

    // stomp
    implementation 'com.github.NaikSoftware:StompProtocolAndroid:1.6.6'


    //rx
    implementation 'io.reactivex.rxjava2:rxjava:2.2.5'
    implementation 'io.reactivex.rxjava2:rxandroid:2.1.0'

    // firebase
    implementation(platform("com.google.firebase:firebase-bom:31.2.2"))

    implementation 'com.google.firebase:firebase-auth-ktx'
    implementation 'com.google.firebase:firebase-database-ktx'
    implementation 'com.google.firebase:firebase-messaging-ktx'

    //
    implementation 'com.github.bishoybasily:stomp:2.0.5'

    implementation 'com.google.android.gms:play-services-auth:20.7.0'

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}